### ISSUE TITLE
Question 2, 12, 15

### ISSUE THREAD

**Issue by fengshuo** [ganqqwerty/123-Essential-JavaScript-Interview-Questions#29] opened 2018-01-20 15:46 UTC
## Question 2
```
var y = 1;
if (function f(){}) {
    y += typeof f;
}
console.log(y);
```

I got `1object` instead of `1undefined`, might be related to this [issue](https://github.com/ganqqwerty/123-Essential-JavaScript-Interview-Question/issues/5)

## Question 12

```
var trees = ["redwood", "bay", "cedar", "oak", "maple"];
delete trees[3];
console.log(trees); // ["redwood", "bay", "cedar", empty, "maple"]; //trees[3] is empty instead of undefined on chrome
```

## Question 15
>Here associativity of the assignment operator is Right to Left so first typeof y will evaluate first which is undefined and assigned to z and then y would be assigned the value of z and then z would be assign value 1.

z should be assign the value of y which is `undefined`

**Comment by ganqqwerty** [comment] 2018-06-22 18:12
Question 2
in which environment did you get `1object` instead of `1undefined`? I tried to run this snippet on Chrome, Firefox, Safari and node.js (all from the console), and in jsfiddle

**Comment by ganqqwerty** [comment] 2018-06-22 18:16
Question 12
Thanks, it's interesting, I didn't know about that! It seems to me that it's just a way of pretty printing the `undefined`, check it out: 

 ```
> trees[3]
undefined
> typeof trees[3]
"undefined"
```

**Comment by ganqqwerty** [comment] 2018-06-22 22:41
Question 15
I didn't understand your comment

**Comment by ganqqwerty** [comment] 2018-08-14 13:44
closing for now. @fengshuo if you can explain what you meant in your comment to Question 15, I will reopen the task and fix whatever the issue is.

**Closed as completed by ganqqwerty** 2018-08-14 13:44 UTC
